---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgBnHn16ScbC3tWgLyS9jLHTAKIAfhxzaNdK4IhoyJHvFcC8M8nMN4CbJ/L5HiZKeP/10PC45yWZJRSEOWsDHz8+g+/2bAom6w1E6dUmBDr/LqKwHkd9iKRY/FcrDf5jjdvCtDVnhki/tXaKPcWvroWmM5lFOvyHk4PEJRHVrxT51SjgG/HAFrTV02TiO8bhaFjsvgObaF3hsjTLMKScRXJfMq8KgW+/q+blCz+WiGpz+JRQg737GjuphrjfM+DMFJe/PH+rQubSI8m9y98nFcEw5llv9tAuZBRL4B4gwsLazJfN4mzsz7NsohsrNA8yrJS5Rt+R6UufPyW5mYWiWZ9Sjnm2IQoSWojiL1s1VeJ3PHwzT5q56ycWkozUSqIcMOPD1j1zGdKPXEBiJoG7S8NoAQJpYKWzg+cjjkov8dsXO4PlTzJ6GDOKq7fcu6Mwx0sEU85xzDdn/3SGQNOqXu26pQUZToeycpKsFMLzn2jtO+TM1dPS0I92QpNXE2nqOHtHAE8Myo3qKM+zeBHtoI2bmczJEWPYwhWDZEMKxzkrV9hqGHYkWZ74o93gOGbZCK5FcZRSk1gYlxjhkoCpQsrbsIj2jEqYTOZ2xJIr7ONdZ5hd0TB5pj+UBB6RwgHWmlpnxra4Bng2ny9GoFmquMKr90DzBPBogxMh6SuHdWi8GFhS/iBPdvcbGwlKw8UYH3gNtIygRELaiOTTlbj/Zq84sysknbOY7qhdgh/tB/RXp+W0BycVcQ==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
