namespace: tenant2-ci
namePrefix: tenant2-
commonLabels:
  variant: tenant2
bases:
- ../../base
patchesStrategicMerge:
- configmap.yml

patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant2-ci
