namespace: tenant1-ci
namePrefix: tenant1-
commonLabels:
  variant: tenant1
bases:
- ../../base
patchesStrategicMerge:
- configmap.yml

patches:
- target:
    kind: Namespace
    name: null
  patch: |-
    - op: replace
      path: /metadata/name
      value: tenant1-ci
