apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: tenant-ci
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Custom Nginx Page for tenant-ci</title>
    </head>
    <body>
        <h1>Welcome to my custom Nginx page!</h1>
    </body>
    </html>
