apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  generators:
  - clusters: {} #Empty map
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: 'https://github.com/svianac/learning-notes.git'
        targetRevision: HEAD
        path: "argocd-apps/nginx-poc-apps-helm/nginx"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
      destination:
        name: "{{name}}"
        namespace: "tenant-ci"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
