apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/svianac/learning-notes.git'
      revision: main
      directories:
      - path: 'argocd-apps/nginx-poc-apps-helm/tenants/*'  
  template:
    metadata:
      name: "{{path.basename}}-nginx"
      labels:
        - managed: argocd
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: 'https://github.com/svianac/learning-notes.git'
        targetRevision: HEAD
        path: "argocd-apps/nginx-poc-apps-helm/nginx"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{path.basename}}"
          valueFiles:
          - "common.yaml"
          - "{{path}}/values.yaml"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "tenant-ci"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
