# nginx.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: nginx
 namespace: argocd
spec:
 project: default
 source:
 repoURL: 'https://gitlab.com/[your username]/samplegitopsapp.git'
 path: manifests
 targetRevision: main
 destination:
 server: 'https://kubernetes.default.svc'
namespace: default
 syncPolicy:
 automated:
 selfHeal: true
 prune: true
