# argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/svianac/learning-notes.git'
    path: argocd-apps/kustomize-as
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
